service: poc-ecr-lambda
frameworkVersion: '3'

custom:
  NodeEnv:
    dev: "development"
    prd: "production"

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  timeout: 90
  memorySize: 2048
  logRetentionInDays: 14
  stage: prd

  environment:
    NODE_ENV: ${self:custom.NodeEnv.${self:provider.stage}}

  ecr:
    images:
      pocImage:
        path: ./

functions:
  api:
    image:
      name: pocImage