service: poc-ecr-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1

  ecr:
    images:
      pocImage:
        path: ./

functions:
  api:
    image:
      name: pocImage

# functions:
#   greeter:
#     image:
#       name: appimage
#       command:
#         - app.greeter
#       entryPoint:
#         - '/lambda-entrypoint.sh'